### Zastosowanie sieci do predykcji cen nieruchomości
Model można wykorzystać do wyceny mieszkań.

Dane użyte w projekcie są syntetyczne i zostały wygenerowane przy pomocy ChatGPT
na potrzeby ćwiczeń analizy danych i budowy modeli ML.

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
#Import biblioteki pozwalającej na utworzenie sieci neuronowej w Pythonie
from tensorflow.keras.models import Sequential, load_model
#Import biblioteki pozwalającej na utworzenie warstw sieci
from tensorflow.keras.layers import Dropout, Dense
#Import biblioteki z funkcjami aktywacji
from tensorflow.keras.activations import elu, exponential, hard_sigmoid, linear, relu, sigmoid, softmax, tanh
#Import biblioteki z miernikami błędu
from tensorflow.keras.losses import binary_crossentropy, categorical_crossentropy, logcosh, poisson
#Import biblioteki z metrykami sukcesu
from tensorflow.keras.metrics import AUC
#Import biblioteki z funkcjami optymalizującymi parametr błędu
from tensorflow.keras.optimizers import Adadelta, Adam, Nadam, RMSprop, SGD, Ftrl
#Import biblioteki pozwalającej na podział zbioru danych na: testowy oraz uczący
from sklearn.model_selection import train_test_split
import tensorflow 
import random

In [2]:
data = pd.read_excel('real_estate_dataset.xlsx')
data.head()

,liczba_pokoi,powierzchnia,pietro,liczba_pieter,rok_budowy,doCentrum_km,standard,winda,balkon,parking,cena
0,1,25.0,2,4,1975,1.25,dobry,1,1,0,529009.00
1,2,49.9,6,8,2007,5.33,dobry,1,0,1,911375.10
2,1,25.0,4,12,1999,7.16,dobry,0,1,1,466071.25
3,2,48.4,2,4,1982,5.72,wysoki,1,1,0,1061614.31
4,2,49.4,10,15,2010,7.81,dobry,1,0,1,1010524.92

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   liczba_pokoi   20000 non-null  int64
 1   powierzchnia   20000 non-null  float64
 2   pietro         20000 non-null  int64
 3   liczba_pieter  20000 non-null  int64
 4   rok_budowy     20000 non-null  int64
 5   doCentrum_km   20000 non-null  float64
 6   standard       20000 non-null  str
 7   winda          20000 non-null  int64
 8   balkon         20000 non-null  int64
 9   parking        20000 non-null  int64
 10  cena           20000 non-null  float64
dtypes: float64(3), int64(7), str(1)
memory usage: 1.7 MB

In [4]:
data["standard"] = data["standard"].map({
    "do_remontu": 0,
    "dobry": 1,
    "wysoki": 2
})

In [5]:
#normalizacja danych w ramce danych
def df_normalizacja(x):
    x  = (x - min(x))/(max(x) - min(x))
    return x

lista = ['liczba_pokoi','powierzchnia','pietro','liczba_pieter','rok_budowy','doCentrum_km','standard','winda','balkon','parking']

X = pd.DataFrame()
for element in lista:
    X[element] = df_normalizacja(data[element])

Y = df_normalizacja(data.cena)

In [6]:
#Podział zbióru danych na uczący i testowy
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=123)

In [7]:
#model

model = Sequential()
model.add(Dense(10,input_dim=X.shape[1],activation=relu))
model.add(Dense(10,activation=relu))
model.add(Dense(1, activation=relu))

model.compile(loss='mean_squared_error',
                optimizer='SGD',
                 metrics=['mse'])

history = model.fit(X_train.values,
                    y_train,
                    epochs=10,
                    batch_size=10)

predictions = model.predict(X_test.values)
score = model.evaluate(X_test, y_test)
print('Test loss:', score[0])

c:\Users\aodob\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/10
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.0116 - mse: 0.0116
Epoch 2/10
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0056 - mse: 0.0056
Epoch 3/10
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0043 - mse: 0.0043
Epoch 4/10
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0038 - mse: 0.0038
Epoch 5/10
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0035 - mse: 0.0035
Epoch 6/10
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0033 - mse: 0.0033
Epoch 7/10
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0032 - mse: 0.0032
Epoch 8/10
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0031 - mse: 0.0031
Epoch 9/10
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0030 - mse: 0.0030
Epoch 10/10
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0029 - mse: 0.0029
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0028 - mse: 0.0028
Test loss: 0.0028427899815142155

In [8]:
# proces uczenia się sieci
loss = history.history['loss']
epochs = range(len(loss))

fig = go.Figure()
fig.add_trace(go.Scatter(x=[*epochs], y=loss,
                    mode='lines', name = 'train'))

fig.show()

In [9]:
#Wizualizacja wyników predykcji oraz faktycznych cen nieruchomości 
fig = go.Figure()
fig.add_trace(go.Scatter(x=predictions.reshape(y_test.shape), y=y_test,
                    mode='markers', name = 'train'))
fig.show()

In [20]:
#Uzyskaj faktyczne wartości predykcji poprzez wymnożenie predykcji z "(data['cena'].max()-data['cena'].min())+ data['cena'].min()" -> odwrócenie normalizacji
predykcja = predictions*(data['cena'].max()-data['cena'].min())+ data['cena'].min()

#Porównaj uzyskane wyniki z rzeczywistymi wartościami
rzeczywiste_wyniki = y_test*(data['cena'].max()-data['cena'].min())+ data['cena'].min()

porownanie = pd.DataFrame(predykcja,rzeczywiste_wyniki).reset_index()
porownanie.rename(columns={'cena':'predykcja',0:'faktyczna_cena'},inplace=True)
porownanie['roznica']=abs(porownanie['predykcja']-porownanie['faktyczna_cena'])

porownanie

       predykcja  faktyczna_cena        roznica
0      626782.18    7.213003e+05   94518.167216
1     1578527.42    1.439304e+06  139223.129394
2     2319737.11    1.765499e+06  554238.173003
3      889823.59    9.751802e+05   85356.562834
4     1111272.64    1.262651e+06  151378.139186
...          ...             ...            ...
3995  1426752.18    1.270408e+06  156343.949931
3996   898786.50    7.729089e+05  125877.640775
3997   998529.10    1.058584e+06   60054.989954
3998   770385.18    8.047350e+05   34349.845354
3999   914975.81    6.365930e+05  278382.764002

[4000 rows x 3 columns]

In [15]:
# sprawdzamy czy model jest wystarczająco dobry

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(porownanie["faktyczna_cena"], porownanie["predykcja"])
print(mae)
print(f"Średni błąd modelu: {mae} zł")

135844.5733992388
Średni błąd modelu: 135844.5733992388 zł

##Wykorzystanie modelu

In [14]:
# nowe mieszkanie
nowe_mieszkanie = X.iloc[[0]].copy()
nowe_mieszkanie[:] = 0

nowe_mieszkanie["powierzchnia"] = 60
nowe_mieszkanie["liczba_pokoi"] = 2
nowe_mieszkanie["liczba_pieter"] = 3

# normalizacja
nowe_mieszkanie_norm = (nowe_mieszkanie - X.min()) / (X.max() - X.min())

# predykcja
pred = model.predict(nowe_mieszkanie_norm)

# odwrócenie normalizacji ceny
cena_min = data["cena"].min()
cena_max = data["cena"].max()

pred_cena = pred * (cena_max - cena_min) + cena_min

print(f"Szacowana cena mieszkania: {pred_cena[0][0]:,.0f} zł")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
Szacowana cena mieszkania: 52,976,090 zł